using System.Reflection;

namespace Nfty.Core.Demo;

/// <summary>
/// The sample CookBook that ships inside nfty: a small collection of layered chests, present in
/// every build and every download, so nobody's first launch is an empty screen.
/// </summary>
/// <remarks>
/// <para><b>It is embedded, not installed beside the executable.</b> nfty ships in four shapes, two
/// of which are a single <c>.exe</c> — a file people copy onto a stick and run somewhere else. A
/// sample that lived next to the binary would be present in two of those four and absent in the two
/// most likely to travel, which makes "always available" a claim rather than a fact. The archive is
/// ~10 KB; carrying it inside the assembly costs nothing and cannot be separated from the app.</para>
///
/// <para><b>The bytes are a build output that is committed</b>, generated by
/// <c>tools/demo/build-demo.py</c> from the art in <c>tools/demo/draw-chest-art.py</c>. That is the
/// same arrangement <c>Themes/Icons.axaml</c> has with <c>assets/icons/*.svg</c>, and for the same
/// reason: the generator is the source, but the app must not need Python to build. <c>DemoCookBook
/// Tests</c> reads, validates and cooks these bytes, so the two cannot drift in silence.</para>
///
/// <para><b>Nothing here writes anywhere by itself.</b> <see cref="WriteTo"/> takes the folder from
/// its caller — a front-end that knows where the user's writable space is — because a Core type that
/// picked its own directory would be reaching into the machine from the one layer that has no
/// business knowing about it.</para>
/// </remarks>
public static class DemoCookBook
{
    /// <summary>The file name the demo is written out as.</summary>
    public const string FileName = "ChestDemo.cbk";

    /// <summary>The CookBook's display name, for a front-end that wants to name it before opening
    /// it.</summary>
    public const string DisplayName = "Chest Demo";

    /// <summary>One line describing what the demo is, for a button caption or a status message.
    /// Stated here rather than in each front-end so the CLI and the GUI say the same thing.</summary>
    public const string Summary =
        "A sample collection of layered chests — two Recipes, all three layer kinds, "
        + "and a few hundred thousand possible assets.";

    private const string ResourceName = "Nfty.Core.Demo." + FileName;

    /// <summary>Opens the embedded archive for reading.</summary>
    /// <returns>A fresh, seekable stream over the <c>.cbk</c> bytes; the caller disposes it.</returns>
    /// <exception cref="InvalidOperationException">The resource is missing from the assembly, which
    /// means the build dropped it — a broken build, not a runtime condition.</exception>
    public static Stream Open() =>
        typeof(DemoCookBook).GetTypeInfo().Assembly.GetManifestResourceStream(ResourceName)
        ?? throw new InvalidOperationException(
            $"The built-in demo CookBook ('{ResourceName}') is missing from this build of Nfty.Core.");

    /// <summary>The embedded archive's bytes.</summary>
    /// <returns>A new array each call, so a caller cannot mutate the copy the next one gets.</returns>
    public static byte[] Bytes()
    {
        using var source = Open();
        using var buffer = new MemoryStream();
        source.CopyTo(buffer);
        return buffer.ToArray();
    }

    /// <summary>
    /// Writes the demo into <paramref name="directory"/> and returns the file's path.
    /// </summary>
    /// <param name="directory">Where to put it. Created if it does not exist.</param>
    /// <param name="overwrite">Whether to replace a copy that is already there. The default is
    /// <c>false</c> — and that default is the point: the demo is meant to be edited, so a second
    /// "open the demo" must hand back the book with the user's changes in it rather than silently
    /// reverting their work. Pass <c>true</c> for an explicit "reset the demo".</param>
    /// <returns>The full path to the archive.</returns>
    public static string WriteTo(string directory, bool overwrite = false)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(directory);
        Directory.CreateDirectory(directory);
        var path = Path.Combine(directory, FileName);
        if (!overwrite && File.Exists(path)) return path;

        // Written through a temporary name and moved into place: a half-written .cbk left by a
        // failure here would be found by the File.Exists above on the next launch and opened as a
        // corrupt archive forever after.
        var staging = path + ".tmp";
        using (var source = Open())
        using (var target = File.Create(staging))
            source.CopyTo(target);
        File.Move(staging, path, overwrite: true);
        return path;
    }
}
