using System.IO.Compression;
using System.Text.Json;
using Nfty.Core.Formats;
using Nfty.Core.Output;

namespace Nfty.Core.Publish;

/// <summary>One file an export will carry, and where it will sit.</summary>
/// <param name="Source">The file on disk now.</param>
/// <param name="Name">Its path inside the export, always with <c>/</c> separators.</param>
/// <param name="Bytes">Its size, so a plan can be totalled without opening anything.</param>
public record ExportEntry(string Source, string Name, long Bytes);

/// <summary>
/// Everything an export will contain, worked out without writing anything.
/// </summary>
/// <remarks>
/// <b>This exists so the sentence a user reads before pressing Export is generated by the code that
/// does the exporting.</b> The alternative — a front-end assembling its own summary from the same
/// checkboxes — is how a screen comes to promise one thing and ship another, and shipping something
/// other than what the screen promised is precisely the defect this whole feature exists to prevent.
/// </remarks>
/// <param name="Entries">Every file, in the order it will be written.</param>
/// <param name="Collection">The collection's name, from <c>set.json</c>.</param>
/// <param name="Count">How many assets the Set holds.</param>
/// <param name="OutputName">The leaf name the export will be given.</param>
public record ExportPlan(
    IReadOnlyList<ExportEntry> Entries, string Collection, int Count, string OutputName)
{
    /// <summary>The total size of everything being shipped.</summary>
    public long Bytes => Entries.Sum(e => e.Bytes);

    /// <summary>
    /// What is going, one line per part — <c>images/  500 files</c>, <c>set.json</c>,
    /// <c>ChestDemo.cbk</c>.
    /// </summary>
    /// <returns>The lines, in <see cref="StringComparer.Ordinal"/> order.</returns>
    /// <remarks>
    /// <b>Named, not counted, and rendered here rather than in each front-end.</b> "Exported 1,502
    /// files" is exactly the sentence that let a packed Set carry its author's source book without
    /// anyone noticing; a reader checks a list of four things and does not check a number. Core
    /// renders it for the reason the reports in <c>Stats/</c> are rendered here — the terminal and
    /// the dialog have to say the identical thing, not something similar.
    /// </remarks>
    public IReadOnlyList<string> Parts() => Entries
        .GroupBy(e => e.Name.Contains('/') ? e.Name[..e.Name.IndexOf('/')] + "/" : e.Name)
        .OrderBy(g => g.Key, StringComparer.Ordinal)
        .Select(g => g.Count() == 1
            ? g.Key
            : string.Create(System.Globalization.CultureInfo.InvariantCulture,
                $"{g.Key}  {g.Count()} files"))
        .ToList();

    /// <summary>The total, for a person: <c>636 KB</c>, <c>1.2 MB</c>.</summary>
    /// <returns>The size as text, invariant like every other figure this product prints.</returns>
    public string SizeText() => Bytes switch
    {
        >= 1024L * 1024 => string.Create(System.Globalization.CultureInfo.InvariantCulture,
            $"{Bytes / 1024.0 / 1024:0.0} MB"),
        >= 1024 => string.Create(System.Globalization.CultureInfo.InvariantCulture,
            $"{Bytes / 1024.0:0} KB"),
        _ => string.Create(System.Globalization.CultureInfo.InvariantCulture, $"{Bytes} bytes"),
    };

    /// <summary>Whether the source CookBook is among the entries — the one inclusion with a
    /// consequence a user should be warned about rather than merely told.</summary>
    public bool CarriesCookBook =>
        Entries.Any(e => e.Name.EndsWith(Archives.CookBookExtension, StringComparison.OrdinalIgnoreCase));
}

/// <summary>What an export produced.</summary>
/// <param name="Path">The folder or file that was written.</param>
/// <param name="Plan">What went into it.</param>
public record ExportResult(string Path, ExportPlan Plan);

/// <summary>
/// Publishes a cooked Set: decides what leaves the machine, and in what shape.
/// </summary>
/// <remarks>
/// <para><b>Why this is not a flag on <c>SetWriter</c>.</b> Writing a Set and publishing one are
/// different operations with different audiences. A cook produces the author's working copy and
/// should hold everything; an export is addressed to somebody — a marketplace, a buyer, a
/// collaborator, a reviewer — and each of those wants a different subset. Folding the second into
/// the first is what produced the defect that motivated this: <c>--pack</c> zipped the output
/// folder rather than the Set, so a cook in a working directory shipped the author's source book
/// inside the archive they handed a buyer.</para>
///
/// <para><b>Sealing is refused as a source.</b> Exporting a <c>.tin</c> is exactly the operation a
/// seal declines, and this is where that policy lives — not in a front-end, which would leave the
/// CLI able to launder a sealed Set back into an open one in a single command.</para>
/// </remarks>
public static class SetExporter
{
    /// <summary>
    /// Works out what an export would contain, without writing anything.
    /// </summary>
    /// <param name="setPath">The Set to export: a folder, or a <c>.set</c> archive.</param>
    /// <param name="options">What to include.</param>
    /// <param name="cookBookPath">The <c>.cbk</c> to ship, when
    /// <see cref="ExportOptions.IncludeCookBook"/> is set.</param>
    /// <returns>The plan.</returns>
    /// <exception cref="ArgumentException">The options ask for something that cannot be built.</exception>
    /// <exception cref="CorruptSetException">The source is not a readable Set.</exception>
    public static ExportPlan Plan(string setPath, ExportOptions options, string? cookBookPath = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(setPath);
        ArgumentNullException.ThrowIfNull(options);
        Validate(options, cookBookPath);

        using var source = OpenSource(setPath);
        return PlanFrom(source.Dir, source.Leaf, options, cookBookPath);
    }

    /// <summary>
    /// Exports a Set.
    /// </summary>
    /// <param name="setPath">The Set to export: a folder, or a <c>.set</c> archive.</param>
    /// <param name="outDir">The folder to write into; created if missing.</param>
    /// <param name="options">What to include, and in what shape.</param>
    /// <param name="cookBookPath">The <c>.cbk</c> to ship, when
    /// <see cref="ExportOptions.IncludeCookBook"/> is set.</param>
    /// <param name="passphrase">Required when <see cref="ExportOptions.Sealed"/> is set.</param>
    /// <returns>Where it landed, and what went into it.</returns>
    /// <exception cref="ArgumentException">The options ask for something that cannot be built.</exception>
    /// <exception cref="SealedSetException">The source is itself sealed, or sealing failed.</exception>
    public static ExportResult Export(string setPath, string outDir, ExportOptions options,
        string? cookBookPath = null, string? passphrase = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(setPath);
        ArgumentException.ThrowIfNullOrWhiteSpace(outDir);
        ArgumentNullException.ThrowIfNull(options);
        Validate(options, cookBookPath);
        if (options.Sealed && !Seal.IsUsablePassphrase(passphrase))
            throw new ArgumentException(
                $"Sealing needs a passphrase of at least {Seal.MinimumPassphraseLength} characters.",
                nameof(passphrase));

        using var source = OpenSource(setPath);
        var plan = PlanFrom(source.Dir, source.Leaf, options, cookBookPath);

        Directory.CreateDirectory(outDir);
        string destination = Path.Combine(Path.GetFullPath(outDir), plan.OutputName);

        // Copying a folder over itself empties it one file at a time. The comparison is on the full
        // path because "." and an absolute path are the same folder and do not look it.
        if (options.Shape == ExportShape.Folder && !options.Sealed
            && string.Equals(Path.TrimEndingDirectorySeparator(destination),
                Path.TrimEndingDirectorySeparator(source.Dir), StringComparison.OrdinalIgnoreCase))
            throw new ArgumentException(
                $"'{destination}' is the Set being exported. Choose a different folder.", nameof(outDir));

        if (options.Shape == ExportShape.Folder) WriteFolder(plan, destination);
        else if (!options.Sealed) WriteArchive(plan, destination);
        else WriteSealed(plan, destination, options, passphrase!);

        return new ExportResult(destination, plan);
    }

    /// <summary>
    /// The rules that make a request buildable at all, checked once for both entry points so
    /// <see cref="Plan"/> cannot describe an export <see cref="Export"/> would refuse.
    /// </summary>
    private static void Validate(ExportOptions options, string? cookBookPath)
    {
        // A sealed folder is a folder of unreadable files: the seal is one authenticated stream, and
        // splitting it across a directory would either leave the files in the clear or leave the
        // recipient with a folder nothing on their machine can open. Refused rather than silently
        // corrected, because quietly changing the shape the user picked is its own defect.
        if (options.Sealed && options.Shape == ExportShape.Folder)
            throw new ArgumentException(
                "A sealed export is a single file. Sealing encrypts the whole Set as one "
                + "authenticated stream, so there is no folder shape for it.", nameof(options));

        if (options.IncludeCookBook && string.IsNullOrWhiteSpace(cookBookPath))
            throw new ArgumentException(
                "This export includes the source CookBook, but no .cbk was given. A Set records its "
                + "book's hash, never the book itself, so the path has to come from the caller.",
                nameof(cookBookPath));

        if (!options.IncludeCookBook || cookBookPath is null) return;
        if (!File.Exists(cookBookPath))
            throw new ArgumentException($"No CookBook at '{cookBookPath}'.", nameof(cookBookPath));
        if (!string.Equals(Path.GetExtension(cookBookPath), Archives.CookBookExtension,
                StringComparison.OrdinalIgnoreCase))
            throw new ArgumentException(
                $"'{cookBookPath}' is not a {Archives.CookBookExtension}.", nameof(cookBookPath));
    }

    /// <summary>A Set opened for reading, whatever shape it arrived in.</summary>
    private sealed record Source(string Dir, string Leaf, string? TempDir) : IDisposable
    {
        public void Dispose()
        {
            if (TempDir is not null && Directory.Exists(TempDir))
                try { Directory.Delete(TempDir, recursive: true); } catch { /* best effort */ }
        }
    }

    private static Source OpenSource(string setPath)
    {
        if (string.Equals(Path.GetExtension(setPath), Archives.SealedExtension, StringComparison.OrdinalIgnoreCase))
            throw new SealedSetException(
                $"'{setPath}' is a sealed export, and re-exporting one is what the seal declines. "
                + "Export from the Set you sealed it from.");

        if (Directory.Exists(setPath))
        {
            if (!SetReader.IsSetFolder(setPath))
                throw new CorruptSetException(setPath,
                    $"'{setPath}' is not a cooked Set - there is no {SetLayout.ManifestFile} in it.");
            string full = Path.TrimEndingDirectorySeparator(Path.GetFullPath(setPath));
            return new Source(full, LeafOf(full), null);
        }

        if (!File.Exists(setPath))
            throw new CorruptSetException(setPath, $"There is no Set at '{setPath}'.");

        var temp = Directory.CreateTempSubdirectory("nfty-export-").FullName;
        try
        {
            ZipFile.ExtractToDirectory(setPath, temp);
            if (!SetReader.IsSetFolder(temp))
                throw new CorruptSetException(setPath,
                    $"'{setPath}' unpacks to something without a {SetLayout.ManifestFile} in it, so "
                    + "it is not a cooked Set.");
            return new Source(temp, Path.GetFileNameWithoutExtension(setPath), temp);
        }
        catch
        {
            try { Directory.Delete(temp, recursive: true); } catch { }
            throw;
        }
    }

    private static string LeafOf(string dir) =>
        Path.GetFileName(dir) is { Length: > 0 } leaf ? leaf : "collection";

    private static ExportPlan PlanFrom(string setDir, string leaf, ExportOptions options,
        string? cookBookPath)
    {
        var manifest = ReadManifest(setDir);
        var wanted = new List<string>(SetLayout.Directories.Count);
        if (options.Images) wanted.Add(SetLayout.ImagesDir);
        if (options.OpenSeaMetadata) wanted.Add(SetLayout.MetadataDir);
        if (options.NftyMetadata) wanted.Add(SetLayout.NftyDir);

        var entries = new List<ExportEntry>();

        // set.json is not optional. It is what makes the result a Set rather than a folder of
        // pictures, it is what `inspect` reads, and it carries the collection-wide rarity table -
        // so even the leanest export still answers "what is this and how rare is what".
        string setJson = SetLayout.ManifestPath(setDir);
        entries.Add(Entry(setJson, SetLayout.ManifestFile));

        foreach (var file in SetLayout.FilesIn(setDir))
        {
            string rel = Path.GetRelativePath(setDir, file).Replace(Path.DirectorySeparatorChar, '/');
            if (rel == SetLayout.ManifestFile) continue;
            if (wanted.Any(d => rel.StartsWith(d + "/", StringComparison.Ordinal)))
                entries.Add(Entry(file, rel));
        }

        if (options.IncludeCookBook && cookBookPath is not null)
            entries.Add(Entry(cookBookPath, Path.GetFileName(cookBookPath)));

        string stem = FileNameFor(manifest.Name, leaf);
        string name = options.Shape == ExportShape.Folder ? stem
            : stem + (options.Sealed ? Archives.SealedExtension : Archives.SetExtension);

        return new ExportPlan(entries, manifest.Name, manifest.Count, name);
    }

    private static ExportEntry Entry(string source, string name) =>
        new(source, name, new FileInfo(source).Length);

    /// <summary>
    /// What the export is called: the COLLECTION's name, not the folder it happened to sit in.
    /// </summary>
    /// <param name="collection">The name from <c>set.json</c>.</param>
    /// <param name="fallback">The source folder's leaf, for a collection whose name is nothing but
    /// characters a filename cannot hold.</param>
    /// <returns>A usable file stem.</returns>
    /// <remarks>
    /// <b>The folder leaf is the wrong answer twice over.</b> A working folder is called whatever
    /// the author typed into a picker — <c>out</c>, <c>test2</c>, <c>final-FINAL</c> — and the
    /// recipient sees that, not the collection. And a Set opened from a packed <c>.set</c> is read
    /// out of a TEMPORARY directory, so the leaf is a random string; exporting an already-open Set
    /// would have produced <c>nfty-set-a3f9c1.set</c>.
    /// </remarks>
    private static string FileNameFor(string collection, string fallback)
    {
        var cleaned = new string(collection
            .Where(c => !Path.GetInvalidFileNameChars().Contains(c)).ToArray()).Trim();
        return cleaned.Length > 0 ? cleaned : fallback;
    }

    /// <summary>
    /// The Set's own manifest, and nothing else.
    /// </summary>
    /// <remarks>
    /// <c>SetReader.Read</c> would answer the same two questions by opening every
    /// <c>nfty/NNNN.json</c> in the collection — ten thousand file reads to learn a name and a
    /// count. The same argument <c>ArchivePeek</c> makes about a CookBook.
    /// </remarks>
    private static SetManifest ReadManifest(string setDir)
    {
        string path = SetLayout.ManifestPath(setDir);
        try
        {
            return JsonSerializer.Deserialize<SetManifest>(File.ReadAllText(path), Json.Options)
                ?? throw new CorruptSetException(path, $"'{path}' is empty.");
        }
        catch (JsonException ex)
        {
            throw new CorruptSetException(path, $"'{path}' is not a readable Set manifest: {ex.Message}");
        }
    }

    private static void WriteFolder(ExportPlan plan, string destination)
    {
        Directory.CreateDirectory(destination);
        foreach (var e in plan.Entries)
        {
            string target = Path.Combine(destination, e.Name.Replace('/', Path.DirectorySeparatorChar));
            Directory.CreateDirectory(Path.GetDirectoryName(target)!);
            File.Copy(e.Source, target, overwrite: true);
        }
    }

    private static void WriteArchive(ExportPlan plan, string destination)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
        if (File.Exists(destination)) File.Delete(destination);
        using var zip = ZipFile.Open(destination, ZipArchiveMode.Create);
        foreach (var e in plan.Entries) zip.CreateEntryFromFile(e.Source, e.Name);
    }

    private static void WriteSealed(ExportPlan plan, string destination, ExportOptions options,
        string passphrase)
    {
        // Packed to a temporary .set first, then encrypted whole. One archive inside one ciphertext,
        // rather than an encrypted entry per file: per-file encryption would leave the file NAMES
        // and every file's exact SIZE in the clear, which for a collection is most of its shape -
        // how many assets, which layers exist, which of them are rare.
        string staging = Path.Combine(Path.GetTempPath(), "nfty-seal-" + Guid.NewGuid().ToString("N") + ".set");
        try
        {
            WriteArchive(plan, staging);
            using var payload = File.OpenRead(staging);
            Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
            Seal.Write(destination, payload, plan.Collection, plan.Count, options.Note,
                SealPolicy.ViewOnly, passphrase);
        }
        finally
        {
            if (File.Exists(staging)) try { File.Delete(staging); } catch { /* best effort */ }
        }
    }
}
