<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>nfty command line</AssemblyTitle>
    <ApplicationIcon>..\Nfty.Desktop\nfty.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nfty.Core\Nfty.Core.csproj" />
  </ItemGroup>

</Project>
