using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Nfty.App.Services;
using Nfty.Core.Publish;

namespace Nfty.App.ViewModels;

/// <summary>One preset tile.</summary>
/// <remarks>
/// <see cref="IsSelected"/> is pushed by the dialog from <see cref="ExportOptions.MatchingPreset"/>
/// rather than set by the click that chose it, so a tile stops being lit the moment a checkbox
/// below it stops agreeing with the preset it names.
/// </remarks>
public partial class ExportPresetTile : ObservableObject
{
    /// <summary>Which preset this tile applies.</summary>
    public ExportPreset Preset { get; }
    /// <summary>Its name.</summary>
    public string Title { get; }
    /// <summary>One sentence saying who it is for. Read from Core, so this and the CLI's help
    /// cannot describe the same choice differently.</summary>
    public string Summary { get; }

    /// <summary>Whether the current options ARE this preset.</summary>
    [ObservableProperty] private bool _isSelected;

    /// <summary>Creates a tile.</summary>
    /// <param name="preset">The preset it applies.</param>
    public ExportPresetTile(ExportPreset preset)
    {
        Preset = preset;
        Title = ExportOptions.TitleOf(preset);
        Summary = ExportOptions.SummaryOf(preset);
    }
}

/// <summary>
/// Deciding what leaves the machine, and doing it.
/// </summary>
/// <remarks>
/// <para><b>The manifest at the bottom is the point of this screen.</b> It names every file that
/// will ship, and it is generated by <see cref="SetExporter.Plan"/> — the same call that then does
/// the writing. A summary assembled here from the same checkboxes would be a second implementation
/// of the rules, and a screen that promises one thing and ships another is exactly the defect this
/// feature exists to prevent: <c>--pack</c> shipped authors' source CookBooks for three releases
/// while the folder on disk looked perfectly correct.</para>
///
/// <para><b>The plan is recomputed on every change, from the OPEN Set's directory.</b>
/// <c>LoadedSet.SourceDirectory</c> is where the files already are — the folder it was opened from,
/// or the temporary directory a <c>.set</c> was unpacked into — so a toggle costs a directory
/// listing rather than re-extracting a ten-thousand-asset archive.</para>
///
/// <para><b>The passphrase lives here and nowhere else.</b> It is not on
/// <see cref="ExportOptions"/>, which is a description of the export that a view model holds, binds
/// and would reasonably be logged while debugging.</para>
/// </remarks>
public partial class ExportDialogViewModel : ViewModelBase
{
    private readonly string _setDirectory;
    private readonly IFilePickerService _picker;
    private readonly IFolderRevealer _revealer;
    private readonly IDialogService _dialogs;

    /// <summary>The four starting points.</summary>
    public IReadOnlyList<ExportPresetTile> Presets { get; } =
        Enum.GetValues<ExportPreset>().Select(p => new ExportPresetTile(p)).ToList();

    [ObservableProperty] private bool _images = true;
    [ObservableProperty] private bool _openSeaMetadata = true;
    [ObservableProperty] private bool _nftyMetadata = true;
    [ObservableProperty] private bool _includeCookBook;
    [ObservableProperty] private bool _packed = true;

    /// <summary>Encrypt the export and mark it view-only.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CanChooseFolder))]
   
    private bool _isSealed;

    /// <summary>The passphrase to seal with. Held here and never put on the options record.</summary>
    [ObservableProperty] private string _passphrase = "";

    /// <summary>Typed a second time. A passphrase mistyped once is a file nobody can ever open,
    /// its author included — there is no recovery path and deliberately no <c>unseal</c>.</summary>
    [ObservableProperty] private string _passphraseConfirm = "";

    /// <summary>What the recipient reads first. Travels in the clear on a sealed export.</summary>
    [ObservableProperty] private string _note = "";

    /// <summary>The <c>.cbk</c> to ship, when the book is included.</summary>
    [ObservableProperty] [NotifyPropertyChangedFor(nameof(CookBookLeaf))]
    private string? _cookBookPath;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ShowForm))]
    [NotifyCanExecuteChangedFor(nameof(ExportCommand))]
    private bool _isRunning;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ShowForm))]
    [NotifyCanExecuteChangedFor(nameof(RevealCommand))]
    private bool _isDone;

    /// <summary>Where the export landed, once it has.</summary>
    [ObservableProperty] private string _outputPath = "";

    /// <summary>What the run produced, as a sentence.</summary>
    [ObservableProperty] private string _resultText = "";

    private string? _written;

    /// <summary>Creates the dialog.</summary>
    /// <param name="setDirectory">Where the open Set's files are —
    /// <c>LoadedSet.SourceDirectory</c>.</param>
    /// <param name="picker">Chooses the destination folder and the CookBook.</param>
    /// <param name="revealer">Opens the destination when the run finishes.</param>
    /// <param name="dialogs">The dialog layer to close through.</param>
    public ExportDialogViewModel(string setDirectory, IFilePickerService picker,
        IFolderRevealer revealer, IDialogService dialogs)
    {
        _setDirectory = setDirectory;
        _picker = picker;
        _revealer = revealer;
        _dialogs = dialogs;
        Refresh();
    }

    /// <summary>
    /// Whether the options form is showing rather than the result.
    /// </summary>
    public bool ShowForm => !IsRunning && !IsDone;

    /// <summary>
    /// Whether this machine can seal at all.
    /// </summary>
    /// <remarks>
    /// AES-GCM is a platform capability, not a language feature, so on a host without it sealing is
    /// not a thing that fails - it is a thing that is not there. The checkbox is disabled rather
    /// than left to accept a passphrase, a confirmation and a note and then throw.
    /// </remarks>
    public bool CanSeal => Seal.IsSupported;

    /// <summary>
    /// Whether the folder shape is available. A sealed export is one authenticated stream, so there
    /// is no folder form of it — the control is disabled rather than silently corrected on Export.
    /// </summary>
    public bool CanChooseFolder => !IsSealed;

    /// <summary>The chosen CookBook's own name, which is the part a reader looks for.</summary>
    public string CookBookLeaf =>
        CookBookPath is { Length: > 0 } p ? Path.GetFileName(p) : "none chosen";

    /// <summary>Every file the export will carry, one line per part.</summary>
    [ObservableProperty] private IReadOnlyList<string> _parts = Array.Empty<string>();

    /// <summary>What it will be called.</summary>
    [ObservableProperty] private string _outputName = "";

    /// <summary>How big it will be.</summary>
    [ObservableProperty] private string _sizeText = "";

    /// <summary>
    /// Why the export cannot run yet, or empty. Shown rather than only disabling the button: a
    /// control that is dim for a reason the screen does not give is a control the user has to guess
    /// at.
    /// </summary>
    [ObservableProperty] [NotifyCanExecuteChangedFor(nameof(ExportCommand))] private string _problem = "";

    /// <summary>
    /// The consequences worth stating rather than merely listing, one line each.
    /// </summary>
    /// <remarks>
    /// <para>These live in the PINNED manifest box rather than beside the controls that cause them,
    /// and that placement was decided on a rendered frame. The seal caveat started inside the seal
    /// panel, which is inside the scroller — so arming the seal pushed the one sentence explaining
    /// what a seal does and does not do below the fold, at the exact moment it mattered. The
    /// manifest never scrolls.</para>
    ///
    /// <para>A list rather than one string because they are not exclusive: an export can carry the
    /// source book AND be sealed, which is the combination most in need of both sentences.</para>
    /// </remarks>
    [ObservableProperty] private IReadOnlyList<string> _consequences = Array.Empty<string>();

    /// <summary>The options as they currently stand.</summary>
    public ExportOptions Options => new()
    {
        Images = Images,
        OpenSeaMetadata = OpenSeaMetadata,
        NftyMetadata = NftyMetadata,
        IncludeCookBook = IncludeCookBook,
        Shape = Packed ? ExportShape.Archive : ExportShape.Folder,
        Sealed = IsSealed,
        Note = string.IsNullOrWhiteSpace(Note) ? null : Note.Trim(),
    };

    /// <summary>Applies a preset. Every box stays editable afterwards — a preset is a starting
    /// point, not a mode.</summary>
    /// <param name="tile">Which preset.</param>
    [RelayCommand]
    private void ApplyPreset(ExportPresetTile? tile)
    {
        if (tile is null) return;
        var o = ExportOptions.For(tile.Preset);
        Images = o.Images;
        OpenSeaMetadata = o.OpenSeaMetadata;
        NftyMetadata = o.NftyMetadata;
        IncludeCookBook = o.IncludeCookBook;
        IsSealed = o.Sealed;
        Packed = o.Shape == ExportShape.Archive;
    }

    /// <summary>Chooses the CookBook to ship.</summary>
    [RelayCommand]
    private async Task PickCookBookAsync()
    {
        var path = await _picker.OpenFileAsync("CookBook to include", ".cbk");
        if (path is null) return;
        CookBookPath = path;
        IncludeCookBook = true;
    }

    partial void OnIsSealedChanged(bool value)
    {
        // Not a silent correction of what the user asked for: the folder control is disabled at the
        // same moment, so the shape they can see is the shape they will get.
        if (value) Packed = true;
    }

    /// <summary>Recomputes what would ship. Called on every change to anything above.</summary>
    private void Refresh()
    {
        UpdateSelectedPreset();
        try
        {
            var plan = SetExporter.Plan(_setDirectory, Options, CookBookPath);
            Parts = plan.Parts();
            OutputName = plan.OutputName;
            SizeText = plan.SizeText();
            var notes = new List<string>();
            if (plan.CarriesCookBook)
                notes.Add("Carries the source CookBook: anyone who opens this can regenerate the "
                    + "collection and cook a different one from your art.");
            if (IsSealed)
                notes.Add("Sealed: unreadable without the passphrase. Anyone you give it to can "
                    + "still take the art - nfty declines, a screenshot does not.");
            if (!Images)
                notes.Add("No art. A metadata drop, useful only where the images are hosted "
                    + "somewhere else.");
            Consequences = notes;
            Problem = SealProblem();
        }
        catch (Exception ex)
        {
            // Whatever Core refuses is stated in its own words rather than restated here, so the
            // dialog cannot disagree with the command line about the same request.
            Parts = Array.Empty<string>();
            OutputName = "";
            SizeText = "";
            Consequences = Array.Empty<string>();
            Problem = ex.Message;
        }
    }

    private string SealProblem()
    {
        if (!IsSealed) return "";
        if (!CanSeal) return Seal.UnsupportedMessage;
        if (!Seal.IsUsablePassphrase(Passphrase))
            return $"A sealing passphrase must be at least {Seal.MinimumPassphraseLength} characters.";
        if (Passphrase != PassphraseConfirm) return "The two passphrases do not match.";
        return "";
    }

    private void UpdateSelectedPreset()
    {
        var live = Options.MatchingPreset();
        foreach (var tile in Presets) tile.IsSelected = tile.Preset == live;
    }

    /// <summary>
    /// Every property the manifest depends on. A change to any of them recomputes it.
    /// </summary>
    /// <remarks>
    /// Named explicitly rather than refreshing on ANY change, because <see cref="Refresh"/> writes
    /// <see cref="Parts"/>, <see cref="OutputName"/> and the rest — which raise changes of their own
    /// and would recur forever. <c>ExportDialogTests</c> derives the list of settable properties by
    /// reflection and fails if one is missing from here, so an input added later cannot quietly stop
    /// updating what the screen promises.
    /// </remarks>
    internal static readonly IReadOnlySet<string> PlanInputs = new HashSet<string>(StringComparer.Ordinal)
    {
        nameof(Images), nameof(OpenSeaMetadata), nameof(NftyMetadata), nameof(IncludeCookBook),
        nameof(Packed), nameof(IsSealed), nameof(Passphrase), nameof(PassphraseConfirm),
        nameof(Note), nameof(CookBookPath),
    };

    /// <summary>Recomputes the manifest whenever anything it depends on changes.</summary>
    /// <param name="e">The property that changed.</param>
    protected override void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
    {
        base.OnPropertyChanged(e);
        if (e.PropertyName is { } name && PlanInputs.Contains(name)) Refresh();
    }

    private bool CanExport() => !IsRunning && Problem.Length == 0;

    /// <summary>Picks a destination and writes the export.</summary>
    [RelayCommand(CanExecute = nameof(CanExport))]
    private async Task ExportAsync()
    {
        var dir = await _picker.PickFolderAsync("Export to folder");
        if (dir is null) return;

        IsRunning = true;
        try
        {
            var options = Options;
            string? passphrase = IsSealed ? Passphrase : null;
            var result = await Task.Run(() =>
                SetExporter.Export(_setDirectory, dir, options, CookBookPath, passphrase));

            _written = result.Path;
            OutputPath = result.Path;
            ResultText = IsSealed
                ? $"Sealed {result.Plan.Count} assets. Send the passphrase by a different route "
                  + "than the file."
                : $"Exported {result.Plan.Count} assets.";
            IsDone = true;
        }
        catch (Exception ex)
        {
            await _dialogs.ShowAsync<object>(
                new ErrorDialogViewModel(_dialogs, "Export failed", ex.Message));
        }
        finally
        {
            IsRunning = false;

            // The passphrase is not kept after the run. It is of no further use here, and the
            // dialog stays alive until the user closes it.
            Passphrase = "";
            PassphraseConfirm = "";
        }
    }

    private bool CanReveal() => IsDone;

    /// <summary>Opens the folder the export landed in.</summary>
    [RelayCommand(CanExecute = nameof(CanReveal))]
    private void Reveal()
    {
        if (_written is null) return;
        _revealer.Reveal(Directory.Exists(_written) ? _written : Path.GetDirectoryName(_written)!);
    }

    /// <summary>Closes the dialog.</summary>
    [RelayCommand]
    private void Close() => _dialogs.Close(null);
}
