using Avalonia.Layout;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Nfty.App.Services;
using Nfty.Core.Formats;
using Nfty.Core.Output;
using Nfty.Core.Imaging;
using Nfty.Core.Publish;

namespace Nfty.App.ViewModels;

/// <summary>One preset tile.</summary>
/// <remarks>
/// <see cref="IsSelected"/> is pushed by the dialog from <see cref="ExportOptions.MatchingPreset"/>
/// rather than set by the click that chose it, so a tile stops being lit the moment a checkbox
/// below it stops agreeing with the preset it names.
/// </remarks>
public partial class ExportPresetTile : ObservableObject
{
    /// <summary>Which preset this tile applies.</summary>
    public ExportPreset Preset { get; }
    /// <summary>Its name.</summary>
    public string Title { get; }
    /// <summary>One sentence saying who it is for. Read from Core, so this and the CLI's help
    /// cannot describe the same choice differently.</summary>
    public string Summary { get; }

    /// <summary>Whether the current options ARE this preset.</summary>
    [ObservableProperty] private bool _isSelected;

    /// <summary>Creates a tile.</summary>
    /// <param name="preset">The preset it applies.</param>
    public ExportPresetTile(ExportPreset preset)
    {
        Preset = preset;
        Title = ExportOptions.TitleOf(preset);
        Summary = ExportOptions.SummaryOf(preset);
    }
}

/// <summary>
/// Deciding what leaves the machine, and doing it.
/// </summary>
/// <remarks>
/// <para><b>The manifest at the bottom is the point of this screen.</b> It names every file that
/// will ship, and it is generated by <see cref="SetExporter.Plan"/> — the same call that then does
/// the writing. A summary assembled here from the same checkboxes would be a second implementation
/// of the rules, and a screen that promises one thing and ships another is exactly the defect this
/// feature exists to prevent: <c>--pack</c> shipped authors' source CookBooks for three releases
/// while the folder on disk looked perfectly correct.</para>
///
/// <para><b>The plan is recomputed on every change, from the OPEN Set's directory.</b>
/// <c>LoadedSet.SourceDirectory</c> is where the files already are — the folder it was opened from,
/// or the temporary directory a <c>.set</c> was unpacked into — so a toggle costs a directory
/// listing rather than re-extracting a ten-thousand-asset archive.</para>
///
/// <para><b>The passphrase lives here and nowhere else.</b> It is not on
/// <see cref="ExportOptions"/>, which is a description of the export that a view model holds, binds
/// and would reasonably be logged while debugging.</para>
/// </remarks>
/// <summary>
/// One corner of the watermark picker, drawn as the corner it is.
/// </summary>
/// <param name="corner">Which corner.</param>
/// <remarks>
/// <b>The control's SHAPE says what it does.</b> Four radio buttons labelled "Top left / Top right
/// / Bottom left / Bottom right" is four strings to read where a 2x2 of squares with the mark in
/// the matching corner is one glance - and this is a debug option, reached by someone who is in a
/// hurry by definition. The alignments live here rather than in the markup so each cell is the same
/// template with the value it was given, the way the preset tiles already work.
/// </remarks>
public partial class CornerOption(StampCorner corner) : ObservableObject
{
    /// <summary>Which corner this cell picks.</summary>
    public StampCorner Corner { get; } = corner;

    /// <summary>Where the mark sits across the cell.</summary>
    public HorizontalAlignment Dot =>
        Corner is StampCorner.TopLeft or StampCorner.BottomLeft
            ? HorizontalAlignment.Left
            : HorizontalAlignment.Right;

    /// <summary>Where the mark sits down the cell.</summary>
    public VerticalAlignment DotV =>
        Corner is StampCorner.TopLeft or StampCorner.TopRight
            ? VerticalAlignment.Top
            : VerticalAlignment.Bottom;

    /// <summary>Whether this is the armed corner.</summary>
    [ObservableProperty] private bool _isSelected;
}

/// <summary>Which page of the export card is showing.</summary>
/// <remarks>
/// <b>Three short pages instead of one long one.</b> The card grew a spritesheet grid and a
/// watermark corner and became the only modal in the app that scrolled its form far enough to hide
/// a control - which is the exact defect the passphrase box was already moved once to escape. The
/// manifest and the footer sit OUTSIDE the tabs, so what is going and what is stopping it are
/// readable from every page: those are the two things a reader must never have to go looking for.
/// </remarks>
public enum ExportTab
{
    /// <summary>What leaves the machine, and in what shape.</summary>
    Contents,

    /// <summary>What is done to the art on the way out.</summary>
    Images,

    /// <summary>Encryption and the note that travels with it.</summary>
    Seal,
}

public partial class ExportDialogViewModel : ViewModelBase
{
    private readonly string _setDirectory;
    private readonly IFilePickerService _picker;
    private readonly IFolderRevealer _revealer;
    private readonly IDialogService _dialogs;
    private readonly string? _recordedSha;

    /// <summary>The four starting points.</summary>
    public IReadOnlyList<ExportPresetTile> Presets { get; } =
        Enum.GetValues<ExportPreset>().Select(p => new ExportPresetTile(p)).ToList();

    [ObservableProperty] private bool _images = true;
    [ObservableProperty] private bool _openSeaMetadata = true;
    [ObservableProperty] private bool _nftyMetadata = true;
    [ObservableProperty] private bool _includeCookBook;
    [ObservableProperty] private bool _packed = true;

    /// <summary>Which page is showing.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(IsContentsTab))]
    [NotifyPropertyChangedFor(nameof(IsImagesTab))]
    [NotifyPropertyChangedFor(nameof(IsSealTab))]
    private ExportTab _tab = ExportTab.Contents;

    /// <summary>Whether the contents page is showing.</summary>
    public bool IsContentsTab => Tab == ExportTab.Contents;
    /// <summary>Whether the images page is showing.</summary>
    public bool IsImagesTab => Tab == ExportTab.Images;
    /// <summary>Whether the seal page is showing.</summary>
    public bool IsSealTab => Tab == ExportTab.Seal;

    /// <summary>Also stitch every asset into one sheet.</summary>
    /// <remarks>
    /// Named for the ACTION rather than the thing, because <c>SpriteSheet</c> is the Core type that
    /// builds it and a property of that name here shadows it inside this class - so
    /// <c>SpriteSheet.ProblemWith</c> would resolve to a bool. A collision a compiler catches is
    /// still a name worth not having.
    /// </remarks>
    [ObservableProperty] private bool _makeSpriteSheet;

    /// <summary>Cells across the sheet.</summary>
    /// <remarks>
    /// <b>Seeded with a real grid rather than left blank or at zero.</b> Core accepts null for
    /// "lay it out for me", and a box showing nothing is a form asking a question the reader has no
    /// opinion about. Ticking the box shows the squarest grid that holds this collection, already
    /// filled in, which is both the answer most people want and an explanation of what the two
    /// numbers mean.
    /// </remarks>
    [ObservableProperty] private int _sheetColumns = 1;

    /// <summary>Cells down the sheet.</summary>
    [ObservableProperty] private int _sheetRows = 1;

    /// <summary>The sheet's pixel size, as the card prints it.</summary>
    [ObservableProperty] private string _sheetSizeText = "";

    /// <summary>Stamp each asset's set number into a corner of its art.</summary>
    [ObservableProperty] private bool _numberWatermark;

    /// <summary>Which corner the stamp sits in.</summary>
    [ObservableProperty] private StampCorner _watermarkCorner = StampCorner.BottomRight;

    /// <summary>The four corners, for the picker.</summary>
    public IReadOnlyList<CornerOption> Corners { get; } =
        Enum.GetValues<StampCorner>().Select(c => new CornerOption(c)).ToList();

    /// <summary>How far the run has got, 0..1.</summary>
    [ObservableProperty] private double _progress;

    /// <summary>What the run is doing, in the words a person would use.</summary>
    [ObservableProperty] private string _phaseText = "";

    /// <summary>Encrypt the export and mark it view-only.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CanChooseFolder))]
   
    private bool _isSealed;

    /// <summary>The passphrase to seal with. Held here and never put on the options record.</summary>
    [ObservableProperty] private string _passphrase = "";

    /// <summary>Typed a second time. A passphrase mistyped once is a file nobody can ever open,
    /// its author included — there is no recovery path and deliberately no <c>unseal</c>.</summary>
    [ObservableProperty] private string _passphraseConfirm = "";

    /// <summary>What the recipient reads first. Travels in the clear on a sealed export.</summary>
    [ObservableProperty] private string _note = "";

    /// <summary>The <c>.cbk</c> to ship, when the book is included.</summary>
    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(CookBookLeaf))]
    [NotifyPropertyChangedFor(nameof(CookBookIsTheSource))]
    private string? _cookBookPath;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ShowForm))]
    [NotifyCanExecuteChangedFor(nameof(ExportCommand))]
    [NotifyCanExecuteChangedFor(nameof(CancelCommand))]
    private bool _isRunning;

    private CancellationTokenSource? _cts;

    [ObservableProperty]
    [NotifyPropertyChangedFor(nameof(ShowForm))]
    [NotifyCanExecuteChangedFor(nameof(RevealCommand))]
    private bool _isDone;

    /// <summary>Where the export landed, once it has.</summary>
    [ObservableProperty] private string _outputPath = "";

    /// <summary>What the run produced, as a sentence.</summary>
    [ObservableProperty] private string _resultText = "";

    private string? _written;

    /// <summary>Creates the dialog.</summary>
    /// <param name="setDirectory">Where the open Set's files are —
    /// <c>LoadedSet.SourceDirectory</c>.</param>
    /// <param name="picker">Chooses the destination folder and the CookBook.</param>
    /// <param name="revealer">Opens the destination when the run finishes.</param>
    /// <param name="dialogs">The dialog layer to close through.</param>
    /// <param name="cookBookSha256">What the Set recorded its book hashing to —
    /// <c>SetManifest.CookbookSha256</c>. Null for a Set that predates the field or was cooked from
    /// a book that never came from a file.</param>
    /// <param name="cookBookCandidates">Paths the app can already name that might be that book: the
    /// open one, recent ones. Books beside the Set are looked at as well, without being asked for.</param>
    public ExportDialogViewModel(string setDirectory, IFilePickerService picker,
        IFolderRevealer revealer, IDialogService dialogs,
        string? cookBookSha256 = null, IEnumerable<string>? cookBookCandidates = null)
    {
        _setDirectory = setDirectory;
        _picker = picker;
        _revealer = revealer;
        _dialogs = dialogs;
        _recordedSha = cookBookSha256;

        // FOUND, NOT ASKED FOR. "Include the source CookBook" used to mean "and now go find the
        // file", which is a question the app can usually answer itself: the Set records its book's
        // hash, so a candidate can be CHECKED rather than guessed at. Nothing is accepted that is
        // not the book, so a wrong one cannot be shipped under that label.
        CookBookPath = CookBookLocator.Find(cookBookSha256,
            (cookBookCandidates ?? Array.Empty<string>()).Concat(CookBookLocator.Nearby(setDirectory)));

        SeedSheetGrid();
        OnWatermarkCornerChanged(WatermarkCorner);
        Refresh();
    }

    /// <summary>
    /// Whether the options form is showing rather than the result.
    /// </summary>
    public bool ShowForm => !IsRunning && !IsDone;

    /// <summary>
    /// Whether this machine can seal at all.
    /// </summary>
    /// <remarks>
    /// AES-GCM is a platform capability, not a language feature, so on a host without it sealing is
    /// not a thing that fails - it is a thing that is not there. The checkbox is disabled rather
    /// than left to accept a passphrase, a confirmation and a note and then throw.
    /// </remarks>
    public bool CanSeal => Seal.IsSupported;

    /// <summary>
    /// Whether the folder shape is available. A sealed export is one authenticated stream, so there
    /// is no folder form of it — the control is disabled rather than silently corrected on Export.
    /// </summary>
    public bool CanChooseFolder => !IsSealed;

    /// <summary>The chosen CookBook's own name, which is the part a reader looks for.</summary>
    public string CookBookLeaf =>
        CookBookPath is { Length: > 0 } p ? Path.GetFileName(p) : "none found - choose one";

    /// <summary>
    /// Whether the chosen CookBook is provably the one this Set was cooked from.
    /// </summary>
    /// <remarks>
    /// Three states, not two. It is the book; it is provably NOT the book; or nothing can be said —
    /// a Set cooked before the field existed, or from a book that never came from a file, records no
    /// hash to compare against. A null on either side is "cannot tell" and must not be reported as
    /// a mismatch, which is the rule <see cref="SetProvenance.Warning"/> already keeps.
    /// </remarks>
    public bool? CookBookIsTheSource => CookBookPath is not { Length: > 0 } path || _recordedSha is null
        ? null
        : SetProvenance.IsSameBook(_recordedSha, HashOf(path));

    private static string? HashOf(string path)
    {
        try { return File.Exists(path) ? CookBookArchive.HashOf(path) : null; }
        catch (IOException) { return null; }
        catch (UnauthorizedAccessException) { return null; }
    }

    /// <summary>Every file the export will carry, one line per part.</summary>
    [ObservableProperty] private IReadOnlyList<string> _parts = Array.Empty<string>();

    /// <summary>What it will be called.</summary>
    [ObservableProperty] private string _outputName = "";

    /// <summary>How big it will be.</summary>
    [ObservableProperty] private string _sizeText = "";

    /// <summary>
    /// Why the export cannot run yet, or empty. Shown rather than only disabling the button: a
    /// control that is dim for a reason the screen does not give is a control the user has to guess
    /// at.
    /// </summary>
    [ObservableProperty] [NotifyCanExecuteChangedFor(nameof(ExportCommand))] private string _problem = "";

    /// <summary>
    /// The consequences worth stating rather than merely listing, one line each.
    /// </summary>
    /// <remarks>
    /// <para>These live in the PINNED manifest box rather than beside the controls that cause them,
    /// and that placement was decided on a rendered frame. The seal caveat started inside the seal
    /// panel, which is inside the scroller — so arming the seal pushed the one sentence explaining
    /// what a seal does and does not do below the fold, at the exact moment it mattered. The
    /// manifest never scrolls.</para>
    ///
    /// <para>A list rather than one string because they are not exclusive: an export can carry the
    /// source book AND be sealed, which is the combination most in need of both sentences.</para>
    /// </remarks>
    [ObservableProperty] private IReadOnlyList<string> _consequences = Array.Empty<string>();

    /// <summary>The options as they currently stand.</summary>
    public ExportOptions Options => new()
    {
        Images = Images,
        OpenSeaMetadata = OpenSeaMetadata,
        NftyMetadata = NftyMetadata,
        IncludeCookBook = IncludeCookBook,
        Shape = Packed ? ExportShape.Archive : ExportShape.Folder,
        Sealed = IsSealed,
        Note = string.IsNullOrWhiteSpace(Note) ? null : Note.Trim(),
        SpriteSheet = MakeSpriteSheet,
        SpriteSheetColumns = MakeSpriteSheet ? SheetColumns : null,
        SpriteSheetRows = MakeSpriteSheet ? SheetRows : null,
        NumberWatermark = NumberWatermark,
        WatermarkCorner = WatermarkCorner,
    };

    /// <summary>Applies a preset. Every box stays editable afterwards — a preset is a starting
    /// point, not a mode.</summary>
    /// <param name="tile">Which preset.</param>
    [RelayCommand]
    private void ApplyPreset(ExportPresetTile? tile)
    {
        if (tile is null) return;
        var o = ExportOptions.For(tile.Preset);
        Images = o.Images;
        OpenSeaMetadata = o.OpenSeaMetadata;
        NftyMetadata = o.NftyMetadata;
        IncludeCookBook = o.IncludeCookBook;
        IsSealed = o.Sealed;
        Packed = o.Shape == ExportShape.Archive;
    }

    /// <summary>Shows a page of the card.</summary>
    /// <param name="tab">Which one.</param>
    [RelayCommand]
    private void ShowTab(ExportTab tab) => Tab = tab;

    /// <summary>Puts the stamp in a corner.</summary>
    /// <param name="corner">Which one.</param>
    /// <remarks>
    /// A command rather than four radio buttons: the picker is a 2x2 of corners drawn as the corners
    /// they are, which is the one control on this card where the SHAPE says what it does and a label
    /// would be the worse answer.
    /// </remarks>
    [RelayCommand]
    private void PickCorner(CornerOption? corner)
    {
        if (corner is not null) WatermarkCorner = corner.Corner;
    }

    partial void OnWatermarkCornerChanged(StampCorner value)
    {
        foreach (var c in Corners) c.IsSelected = c.Corner == value;
    }

    /// <summary>Chooses the CookBook to ship.</summary>
    [RelayCommand]
    private async Task PickCookBookAsync()
    {
        var path = await _picker.OpenFileAsync("CookBook to include", ".cbk");
        if (path is null) return;
        CookBookPath = path;
        IncludeCookBook = true;
    }

    partial void OnIsSealedChanged(bool value)
    {
        // Not a silent correction of what the user asked for: the folder control is disabled at the
        // same moment, so the shape they can see is the shape they will get.
        if (value) Packed = true;
    }

    /// <summary>Recomputes what would ship. Called on every change to anything above.</summary>
    private void Refresh()
    {
        UpdateSelectedPreset();
        try
        {
            var plan = SetExporter.Plan(_setDirectory, Options, CookBookPath);
            Parts = plan.Parts();
            OutputName = plan.OutputName;
            SizeText = plan.SizeText();
            var notes = new List<string>();
            if (plan.CarriesCookBook)
                notes.Add("Carries the source CookBook: anyone who opens this can regenerate the "
                    + "collection and cook a different one from your art.");

            // A WARNING, NEVER A REFUSAL - the same rule `extend` keeps about the same comparison.
            // Shipping a book that did not cook this Set is a legitimate thing to want, and the
            // author is the one who knows; shipping one BELIEVING it is the source is not, and
            // nothing else on this screen would have said so.
            if (IncludeCookBook && CookBookIsTheSource == false)
                notes.Add("That CookBook is not the one this Set was cooked from: its hash differs "
                    + "from the one set.json recorded. Cooking from it produces a different "
                    + "collection, not this one.");
            if (IsSealed)
                notes.Add("Sealed: unreadable without the passphrase. Anyone you give it to can "
                    + "still take the art - nfty declines, a screenshot does not.");
            if (!Images)
                notes.Add("No art. A metadata drop, useful only where the images are hosted "
                    + "somewhere else.");
            if (!Images && MakeSpriteSheet)
                notes.Add("The sheet is stitched from art this export is not carrying. It ships "
                    + "alone, which is a contact sheet rather than a collection.");
            if (NumberWatermark)
                notes.Add("Numbered art: the set number is painted into every asset and into the "
                    + "sheet. A debug copy, not a mintable one.");
            Consequences = notes;

            SheetSizeText = plan.SpriteSheet is { } sheet
                ? $"{sheet.SizeText()} px"
                : "";

            // The grid's own problem is reported through the SAME footer the seal uses, so a
            // refusal reads the same wherever it came from - and Core words it, so the dialog and
            // the command line cannot disagree about the same grid.
            Problem = SheetProblem() is { Length: > 0 } grid ? grid : SealProblem();
        }
        catch (Exception ex)
        {
            // Whatever Core refuses is stated in its own words rather than restated here, so the
            // dialog cannot disagree with the command line about the same request.
            Parts = Array.Empty<string>();
            OutputName = "";
            SizeText = "";
            Consequences = Array.Empty<string>();
            Problem = ex.Message;
        }
    }

    /// <summary>
    /// Fills the grid boxes with the layout Core would pick, so the page opens on a real answer.
    /// </summary>
    /// <remarks>
    /// Asked of <c>SetExporter.Plan</c> rather than worked out here, so the numbers the boxes show
    /// are the numbers the export would use - the same rule the manifest strip below follows. A Set
    /// that cannot be planned at all leaves the 1x1 default and the footer says why.
    /// </remarks>
    private void SeedSheetGrid()
    {
        try
        {
            var plan = SetExporter.Plan(_setDirectory, Options with { SpriteSheet = true }, null);
            if (plan.SpriteSheet is { } layout)
            {
                SheetColumns = layout.Columns;
                SheetRows = layout.Rows;
            }
        }
        catch (Exception ex) when (ex is ArgumentException or IOException
                                       or UnauthorizedAccessException or CorruptSetException)
        {
            // Left at the default. Refresh() reports whatever is actually wrong with the Set.
        }
    }

    /// <summary>Why the chosen grid cannot be built, or empty.</summary>
    private string SheetProblem()
    {
        if (!MakeSpriteSheet) return "";
        try
        {
            var plan = SetExporter.Plan(_setDirectory, Options, CookBookPath);
            return plan.SpriteSheet is { } layout
                ? SpriteSheet.ProblemWith(layout, plan.Count) ?? ""
                : "";
        }
        catch (Exception ex) when (ex is ArgumentException or IOException
                                       or UnauthorizedAccessException or CorruptSetException)
        {
            return "";
        }
    }

    private string SealProblem()
    {
        if (!IsSealed) return "";
        if (!CanSeal) return Seal.UnsupportedMessage;
        if (!Seal.IsUsablePassphrase(Passphrase))
            return $"A sealing passphrase must be at least {Seal.MinimumPassphraseLength} characters.";
        if (Passphrase != PassphraseConfirm) return "The two passphrases do not match.";
        return "";
    }

    private void UpdateSelectedPreset()
    {
        var live = Options.MatchingPreset();
        foreach (var tile in Presets) tile.IsSelected = tile.Preset == live;
    }

    /// <summary>
    /// Every property the manifest depends on. A change to any of them recomputes it.
    /// </summary>
    /// <remarks>
    /// Named explicitly rather than refreshing on ANY change, because <see cref="Refresh"/> writes
    /// <see cref="Parts"/>, <see cref="OutputName"/> and the rest — which raise changes of their own
    /// and would recur forever. <c>ExportDialogTests</c> derives the list of settable properties by
    /// reflection and fails if one is missing from here, so an input added later cannot quietly stop
    /// updating what the screen promises.
    /// </remarks>
    internal static readonly IReadOnlySet<string> PlanInputs = new HashSet<string>(StringComparer.Ordinal)
    {
        nameof(Images), nameof(OpenSeaMetadata), nameof(NftyMetadata), nameof(IncludeCookBook),
        nameof(Packed), nameof(IsSealed), nameof(Passphrase), nameof(PassphraseConfirm),
        nameof(Note), nameof(CookBookPath), nameof(MakeSpriteSheet), nameof(SheetColumns),
        nameof(SheetRows), nameof(NumberWatermark), nameof(WatermarkCorner),
    };

    /// <summary>Recomputes the manifest whenever anything it depends on changes.</summary>
    /// <param name="e">The property that changed.</param>
    protected override void OnPropertyChanged(System.ComponentModel.PropertyChangedEventArgs e)
    {
        base.OnPropertyChanged(e);
        if (e.PropertyName is { } name && PlanInputs.Contains(name)) Refresh();
    }

    private bool CanExport() => !IsRunning && Problem.Length == 0;

    /// <summary>Picks a destination and writes the export.</summary>
    [RelayCommand(CanExecute = nameof(CanExport))]
    private async Task ExportAsync()
    {
        var dir = await _picker.PickFolderAsync("Export to folder");
        if (dir is null) return;

        IsRunning = true;
        Progress = 0;
        PhaseText = "Starting...";
        _cts = new CancellationTokenSource();
        try
        {
            var options = Options;
            string? passphrase = IsSealed ? Passphrase : null;

            // A REAL BAR, NOT AN INDETERMINATE ONE. This used to spin whatever the run was doing,
            // which is the right answer only while nothing can report - and every step of an export
            // can. A stamped, stitched export of a large collection is minutes of work, and a
            // barber pole for minutes is indistinguishable from a hang.
            var reporter = new Progress<ExportProgress>(p =>
            {
                Progress = p.Fraction;
                PhaseText = p.Phase;
            });

            var result = await SetExporter.ExportAsync(_setDirectory, dir, options, CookBookPath,
                passphrase, reporter, _cts.Token);

            _written = result.Path;
            OutputPath = result.Path;
            ResultText = IsSealed
                ? $"Sealed {result.Plan.Count} assets. Send the passphrase by a different route "
                  + "than the file."
                : $"Exported {result.Plan.Count} assets.";
            IsDone = true;
        }
        catch (OperationCanceledException)
        {
            PhaseText = "Canceled";
        }
        catch (Exception ex)
        {
            await _dialogs.ShowAsync<object>(
                new ErrorDialogViewModel(_dialogs, "Export failed", ex.Message));
        }
        finally
        {
            IsRunning = false;
            _cts?.Dispose();
            _cts = null;

            // The passphrase is not kept after the run. It is of no further use here, and the
            // dialog stays alive until the user closes it.
            Passphrase = "";
            PassphraseConfirm = "";
        }
    }

    /// <summary>Stops the run at the next step.</summary>
    /// <remarks>
    /// Between steps rather than mid-file, so a canceled export never leaves a half-written PNG
    /// behind - the same position the cook dialog takes about an asset.
    /// </remarks>
    [RelayCommand(CanExecute = nameof(CanCancel))]
    private void Cancel() => _cts?.Cancel();

    private bool CanCancel() => IsRunning;

    private bool CanReveal() => IsDone;

    /// <summary>Opens the folder the export landed in.</summary>
    [RelayCommand(CanExecute = nameof(CanReveal))]
    private void Reveal()
    {
        if (_written is null) return;
        _revealer.Reveal(Directory.Exists(_written) ? _written : Path.GetDirectoryName(_written)!);
    }

    /// <summary>Closes the dialog.</summary>
    [RelayCommand]
    private void Close() => _dialogs.Close(null);
}
